[2024-04-29T09:27:12.907+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T09:27:12.934+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: immo_eliza.collection manual__2024-04-29T09:27:10.137874+00:00 [queued]>
[2024-04-29T09:27:12.945+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: immo_eliza.collection manual__2024-04-29T09:27:10.137874+00:00 [queued]>
[2024-04-29T09:27:12.947+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T09:27:12.964+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collection> on 2024-04-29 09:27:10.137874+00:00
[2024-04-29T09:27:12.972+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T09:27:12.975+0000] {standard_task_runner.py:63} INFO - Started process 93 to run task
[2024-04-29T09:27:12.974+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'immo_eliza', 'collection', 'manual__2024-04-29T09:27:10.137874+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/eliza.py', '--cfg-path', '/tmp/tmpa09iyfyg']
[2024-04-29T09:27:12.977+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask collection
[2024-04-29T09:27:13.033+0000] {task_command.py:426} INFO - Running <TaskInstance: immo_eliza.collection manual__2024-04-29T09:27:10.137874+00:00 [running]> on host 2f572e0ad8bc
[2024-04-29T09:27:13.150+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='immo_eliza' AIRFLOW_CTX_TASK_ID='collection' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T09:27:10.137874+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T09:27:10.137874+00:00'
[2024-04-29T09:27:13.151+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T09:27:13.168+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-29T09:27:13.170+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\ncd ..../opt/***/dags/eliza/collection/scrapy\nscrapy crawl immoweb']
[2024-04-29T09:27:13.183+0000] {subprocess.py:86} INFO - Output:
[2024-04-29T09:27:13.185+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 2: cd: ..../opt/***/dags/eliza/collection/scrapy: No such file or directory
[2024-04-29T09:27:14.917+0000] {subprocess.py:93} INFO - Scrapy 2.11.1 - no active project
[2024-04-29T09:27:14.918+0000] {subprocess.py:93} INFO - 
[2024-04-29T09:27:14.920+0000] {subprocess.py:93} INFO - Unknown command: crawl
[2024-04-29T09:27:14.922+0000] {subprocess.py:93} INFO - 
[2024-04-29T09:27:14.923+0000] {subprocess.py:93} INFO - Use "scrapy" to see available commands
[2024-04-29T09:27:15.131+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-29T09:27:15.140+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T09:27:15.172+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-29T09:27:15.184+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=immo_eliza, task_id=collection, execution_date=20240429T092710, start_date=20240429T092712, end_date=20240429T092715
[2024-04-29T09:27:15.211+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task collection (Bash command failed. The command returned a non-zero exit code 2.; 93)
[2024-04-29T09:27:15.240+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T09:27:15.280+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T09:27:15.291+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
