[2024-04-29T09:10:42.996+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T09:10:43.036+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: immo_eliza.collection scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-29T09:10:43.049+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: immo_eliza.collection scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-29T09:10:43.050+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T09:10:43.072+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collection> on 2024-04-25 00:00:00+00:00
[2024-04-29T09:10:43.087+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=157) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T09:10:43.089+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2024-04-29T09:10:43.089+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'immo_eliza', 'collection', 'scheduled__2024-04-25T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/eliza.py', '--cfg-path', '/tmp/tmpmy3ealia']
[2024-04-29T09:10:43.092+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask collection
[2024-04-29T09:10:43.155+0000] {task_command.py:426} INFO - Running <TaskInstance: immo_eliza.collection scheduled__2024-04-25T00:00:00+00:00 [running]> on host 2f572e0ad8bc
[2024-04-29T09:10:43.269+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='immo_eliza' AIRFLOW_CTX_TASK_ID='collection' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-25T00:00:00+00:00'
[2024-04-29T09:10:43.271+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T09:10:43.317+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-29T09:10:43.318+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd collection; cd scrapy; scrapy crawl immoweb']
[2024-04-29T09:10:43.337+0000] {subprocess.py:86} INFO - Output:
[2024-04-29T09:10:43.347+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: collection: No such file or directory
[2024-04-29T09:10:43.348+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: scrapy: No such file or directory
[2024-04-29T09:10:45.390+0000] {subprocess.py:93} INFO - Scrapy 2.11.1 - no active project
[2024-04-29T09:10:45.391+0000] {subprocess.py:93} INFO - 
[2024-04-29T09:10:45.392+0000] {subprocess.py:93} INFO - Unknown command: crawl
[2024-04-29T09:10:45.393+0000] {subprocess.py:93} INFO - 
[2024-04-29T09:10:45.394+0000] {subprocess.py:93} INFO - Use "scrapy" to see available commands
[2024-04-29T09:10:45.515+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-29T09:10:45.516+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T09:10:45.531+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-29T09:10:45.537+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=immo_eliza, task_id=collection, execution_date=20240425T000000, start_date=20240429T091043, end_date=20240429T091045
[2024-04-29T09:10:45.555+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task collection (Bash command failed. The command returned a non-zero exit code 2.; 193)
[2024-04-29T09:10:45.592+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T09:10:45.622+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T09:10:45.628+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
