[2024-04-29T09:10:44.857+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T09:10:44.889+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: immo_eliza.collection scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T09:10:44.901+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: immo_eliza.collection scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T09:10:44.902+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T09:10:44.921+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collection> on 2024-04-28 00:00:00+00:00
[2024-04-29T09:10:44.933+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=168) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T09:10:44.936+0000] {standard_task_runner.py:63} INFO - Started process 219 to run task
[2024-04-29T09:10:44.935+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'immo_eliza', 'collection', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/eliza.py', '--cfg-path', '/tmp/tmpni6yvocj']
[2024-04-29T09:10:44.939+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask collection
[2024-04-29T09:10:45.003+0000] {task_command.py:426} INFO - Running <TaskInstance: immo_eliza.collection scheduled__2024-04-28T00:00:00+00:00 [running]> on host 2f572e0ad8bc
[2024-04-29T09:10:45.119+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='immo_eliza' AIRFLOW_CTX_TASK_ID='collection' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2024-04-29T09:10:45.121+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T09:10:45.139+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-29T09:10:45.142+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd collection; cd scrapy; scrapy crawl immoweb']
[2024-04-29T09:10:45.164+0000] {subprocess.py:86} INFO - Output:
[2024-04-29T09:10:45.166+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: collection: No such file or directory
[2024-04-29T09:10:45.166+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: scrapy: No such file or directory
[2024-04-29T09:10:46.530+0000] {subprocess.py:93} INFO - Scrapy 2.11.1 - no active project
[2024-04-29T09:10:46.531+0000] {subprocess.py:93} INFO - 
[2024-04-29T09:10:46.532+0000] {subprocess.py:93} INFO - Unknown command: crawl
[2024-04-29T09:10:46.532+0000] {subprocess.py:93} INFO - 
[2024-04-29T09:10:46.533+0000] {subprocess.py:93} INFO - Use "scrapy" to see available commands
[2024-04-29T09:10:46.651+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-29T09:10:46.652+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T09:10:46.665+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-29T09:10:46.672+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=immo_eliza, task_id=collection, execution_date=20240428T000000, start_date=20240429T091044, end_date=20240429T091046
[2024-04-29T09:10:46.691+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task collection (Bash command failed. The command returned a non-zero exit code 2.; 219)
[2024-04-29T09:10:46.717+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T09:10:46.755+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T09:10:46.765+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
